### ISSUE TITLE
Explicit authors

### ISSUE THREAD

**Issue by koppor** [citation-style-language/locales#151]
(Similar request as https://github.com/citation-style-language/styles/issues/2372)

I aim to support getting the CSL styles packaged for debian so that they are available for [JabRef ](https://www.jabref.org/). Debian pays attention that the authors of contributions are properly attributed.

CC-BY requests that the original authors are mentioned. Is it possible to include the author at each XML file? For instance, https://github.com/citation-style-language/locales/blob/master/locales-tr-TR.xml does not show an author and there also doesn't seem an AUTHORS file in the root of the repository.

**Comment by rmzelle** [comment]
@koppor, I'll see if I can add some acknowledgments to locale files that haven't any.

(note that before CSL 1.0.1 it was not even possible to have attribution within locale files, so we're probably more delinquent in this repo. See http://docs.citationstyles.org/en/stable/release-notes.html#locale-metadata)

> CC-BY requests that the original authors are mentioned.

Just to add to my previous comments: the main reason we went with the BY-SA variant is that we wished to deter commercial products from taking all CSL styles/locales, stripping all author/contribution information, and removing any mention of the CSL project. As long as author/contribution information is kept intact, and a link to the CSL project is provided, we as maintainers are fully satisfied. I think that's a reasonable interpretation of the license, without requiring that every file contains a comprehensive list of people who contributed any changes (but then again, I Am Not A Lawyer).

cc @adam3smith, @fbennett, @bdarcus, @gregoa.

**Comment by rmzelle** [comment]
Actually, it looks like 42 out of 52 locale files currently don't have any translators listed, so it would be quite a bit of work to dig up all the committer info. (according to `grep -E -L '(<translator>)' *.xml | wc -l`)

**Comment by gregoa** [comment]
On Sat, 24 Dec 2016 11:13:00 -0800, Rintze M. Zelle wrote:

> I think that's a reasonable
> interpretation of the license, without requiring that every file
> contains a comprehensive list of people who contributed any changes
> (but then again, I Am Not A Lawyer).

The question is still who is able to grant this license, i.e. who
is/are the copyright holder(s). And since it's not the CSL project
this can only be the individual authors.

(Note that this is not about lists of contributions or changes but
about legal "ownership".)
 

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Nico: Abschied

**Comment by rmzelle** [comment]
> The question is still who is able to grant this license, i.e. who is/are the copyright holder(s). And since it's not the CSL project this can only be the individual authors. (Note that this is not about lists of contributions or changes but about legal "ownership".)

Right. I guess the best we have is implicit approval by contributors, since every style and locale file, as well as our contributing guidelines, clearly shows the license. We've also discussed licensing several times on the CSL mailing list, and I don't think anybody ever raised issues about their past contributions. We could be a bit more explicit in our documentation, but otherwise I share the opinion expressed at http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html.
